os: osx
osx_image: xcode12.5
language: shell

before_install:
  - brew install python
  - pip install -r requirements.txt

install:
  - pip install pyinstaller

script:
- pyinstaller --onefile filtWA.py --noconsole --windowed --clean --add-data="wa.png:img" -n Filter_BOTC --target-arch=universal2
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/
  on:
    branch: master
